# Generated by Django 3.2.2 on 2021-05-08 08:54

import api.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=60, validators=[api.models.WhitelistEmailValidator(whitelist=['gmail.com', 'yahoo.com', 'hotmail.com'])])),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Phone Number')),
                ('detail', models.TextField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('flat', 'Flat'), ('room', 'Room'), ('house', 'House')], max_length=5)),
                ('title', models.CharField(max_length=32)),
                ('img1', models.ImageField(default='images/data/default.png', upload_to='images/data/', verbose_name='')),
                ('img2', models.ImageField(default='images/data/default.png', upload_to='images/data/', verbose_name='')),
                ('img3', models.ImageField(default='images/data/default.png', upload_to='images/data/', verbose_name='')),
                ('img4', models.ImageField(default='images/data/default.png', upload_to='images/data/', verbose_name='')),
                ('description', models.TextField(max_length=360)),
                ('bedroom', models.IntegerField(blank=True, null=True)),
                ('bathroom', models.IntegerField(blank=True, null=True)),
                ('balconies', models.IntegerField(blank=True, null=True)),
                ('Kitchen', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('parking', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('gas_pipeline', models.BooleanField(default=False)),
                ('electricity_charge', models.IntegerField(blank=True, default=0)),
                ('electricity_supply', models.BooleanField(default=True)),
                ('Power_backup', models.BooleanField(default=False)),
                ('water_charge', models.IntegerField(blank=True, default=0)),
                ('water_supply', models.BooleanField(default=True)),
                ('water_purifier', models.BooleanField(default=False)),
                ('fridge', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('CCTV', models.BooleanField(default=False)),
                ('guard', models.BooleanField(default=False)),
                ('medical', models.BooleanField(default=False)),
                ('fire_alarme', models.BooleanField(default=False)),
                ('cleaning', models.CharField(blank=True, choices=[('no', 'No'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='no', max_length=6)),
                ('furnished', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semifurnished', 'Semifurnished'), ('fullyfurnished', 'Fullyfurnished')], default='unfurnished', max_length=20)),
                ('available_for', models.CharField(blank=True, choices=[('bachelor', 'bachelor'), ('student', 'student'), ('couple', 'couple'), ('family', 'family'), ('boys', 'boys'), ('girls', 'girls'), ('any', 'any')], default='any', max_length=10)),
                ('available_from', models.DateField()),
                ('rent', models.IntegerField()),
                ('additional_charge', models.IntegerField(blank=True, default=0)),
                ('security_money', models.IntegerField(blank=True, default=0)),
                ('one_time_charge', models.IntegerField(blank=True, default=0)),
                ('agreement_duration', models.IntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(max_length=40)),
                ('owner_phone_no1', models.CharField(max_length=10)),
                ('owner_phone_no2', models.CharField(blank=True, max_length=10)),
                ('posted_by', models.CharField(choices=[('owner', 'Owner'), ('agent', 'Agent')], max_length=5)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('agent_name', models.CharField(blank=True, max_length=40, null=True)),
                ('age_of_property', models.IntegerField(blank=True, null=True)),
                ('locality', models.TextField(blank=True, max_length=360, null=True)),
                ('address', models.TextField(max_length=360)),
                ('city', models.TextField(max_length=360)),
                ('state', models.TextField(max_length=360)),
                ('pin', models.TextField(max_length=360)),
            ],
        ),
    ]
