# Generated by Django 3.1.7 on 2021-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('floor', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('balconies', models.IntegerField()),
                ('area', models.IntegerField()),
                ('furnished', models.BooleanField()),
                ('price', models.IntegerField()),
                ('additional_charge', models.IntegerField()),
                ('security_money', models.IntegerField()),
                ('locality', models.TextField(max_length=360)),
                ('address', models.TextField(max_length=360)),
                ('city', models.TextField(max_length=360)),
                ('state', models.TextField(max_length=360)),
                ('pin', models.TextField(max_length=360)),
                ('phone', models.TextField(max_length=10)),
                ('available', models.TextField(max_length=360)),
                ('parking', models.BooleanField()),
                ('agreement_duration', models.IntegerField()),
                ('description', models.TextField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('balconies', models.IntegerField()),
                ('area', models.IntegerField()),
                ('furnished', models.BooleanField()),
                ('price', models.IntegerField()),
                ('additional_charge', models.IntegerField()),
                ('security_money', models.IntegerField()),
                ('locality', models.TextField(max_length=360)),
                ('address', models.TextField(max_length=360)),
                ('city', models.TextField(max_length=360)),
                ('state', models.TextField(max_length=360)),
                ('pin', models.TextField(max_length=360)),
                ('phone', models.TextField(max_length=10)),
                ('available', models.TextField(max_length=360)),
                ('parking', models.BooleanField()),
                ('agreement_duration', models.IntegerField()),
                ('description', models.TextField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('bathroom', models.IntegerField()),
                ('balconies', models.IntegerField()),
                ('area', models.IntegerField()),
                ('furnished', models.BooleanField()),
                ('ac', models.BooleanField()),
                ('water', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('additional_charge', models.IntegerField()),
                ('security_money', models.IntegerField()),
                ('locality', models.TextField(max_length=360)),
                ('address', models.TextField(max_length=360)),
                ('city', models.TextField(max_length=360)),
                ('state', models.TextField(max_length=360)),
                ('pin', models.TextField(max_length=360)),
                ('phone', models.TextField(max_length=10)),
                ('available', models.TextField(max_length=360)),
                ('parking', models.BooleanField()),
                ('agreement_duration', models.IntegerField()),
                ('description', models.TextField(max_length=360)),
            ],
        ),
    ]
