# Generated by Django 4.0.6 on 2022-07-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='available_from',
            field=models.DateField(),
        ),
    ]
