# Generated by Django 3.2.2 on 2021-06-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='parking',
            field=models.BooleanField(default=True),
        ),
    ]
