# Generated by Django 3.1.7 on 2021-04-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='img2',
            field=models.IntegerField(),
        ),
    ]
