# Generated by Django 3.2.2 on 2021-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_datamodel_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='bhk',
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Kitchen',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='age_of_property',
            field=models.IntegerField(blank=True, default='Not available', null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='agreement_duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='area',
            field=models.IntegerField(blank=True, default='Data unavailabe', null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='available_for',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('GovernmentEmployee', 'GovernmentEmployee'), ('Bachelor', 'Bachelor'), ('Couple', 'Couple'), ('Family', 'Family'), ('Boy', 'Boy'), ('Girl', 'Girl'), ('Any', 'Any')], default='Any', max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='balconies',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='bathroom',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='bedroom',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='cleaning',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], default='No', max_length=6),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='furnished',
            field=models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('SemiFurnished', 'Semifurnished'), ('FullyFurnished', 'Fullyfurnished')], default='Unfurnished', max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='img1',
            field=models.ImageField(blank=True, default='images/data/default.png', upload_to='images/data/'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='img2',
            field=models.ImageField(blank=True, default='images/data/default.png', upload_to='images/data/'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='img3',
            field=models.ImageField(blank=True, default='images/data/default.png', upload_to='images/data/'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='img4',
            field=models.ImageField(blank=True, default='images/data/default.png', upload_to='images/data/'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
