# Generated by Django 3.1.7 on 2021-04-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210409_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='img2',
            field=models.ImageField(upload_to=''),
        ),
    ]
