# Generated by Django 3.1.7 on 2021-04-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210409_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img1',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='img2',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
