# Generated by Django 3.1.7 on 2021-04-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210410_0827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='flat',
            name='img1',
            field=models.ImageField(null=True, upload_to='images/flat/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='flat',
            name='img2',
            field=models.ImageField(null=True, upload_to='images/flat/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='flat',
            name='img3',
            field=models.ImageField(null=True, upload_to='images/flat/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='flat',
            name='img4',
            field=models.ImageField(null=True, upload_to='images/flat/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='house',
            name='img1',
            field=models.ImageField(null=True, upload_to='images/house/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='house',
            name='img2',
            field=models.ImageField(null=True, upload_to='images/house/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='house',
            name='img3',
            field=models.ImageField(null=True, upload_to='images/house/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='house',
            name='img4',
            field=models.ImageField(null=True, upload_to='images/house/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='room',
            name='img1',
            field=models.ImageField(null=True, upload_to='images/room/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='room',
            name='img2',
            field=models.ImageField(null=True, upload_to='images/room/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='room',
            name='img3',
            field=models.ImageField(null=True, upload_to='images/room/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='room',
            name='img4',
            field=models.ImageField(null=True, upload_to='images/room/', verbose_name=''),
        ),
    ]
