from .models import DataModel

# change all these before run
# n u l l  =  None
# t r u e  =  True
# f a l s e  =  False
# change all img field with image location (location must be in media folder)


datas=[
    {
        "id": 1,
        "property_type": "House",
        "title": "Rainbow House",
        "img1": "D:\RentAssure\RentAssure-Backend\media\\raw\\1.jpeg",
        "img2": "D:\RentAssure\RentAssure-Backend\media\\raw\\2.jpeg",
        "img3": "D:\RentAssure\RentAssure-Backend\media\\raw\\3.jpeg",
        "img4": "D:\RentAssure\RentAssure-Backend\media\\raw\\4.jpeg",
        "description": "It is a beautiful house with magical view outside.",
        "bhk": "3BHK",
        "bedroom": 3,
        "bathroom": 4,
        "balconies": 2,
        "Kitchen": 1,
        "area": 2300,
        "parking": True,
        "lift": False,
        "swimming_pool": False,
        "gym": False,
        "gas_pipeline": True,
        "electricity_charge": 1500,
        "electricity_supply": True,
        "Power_backup": False,
        "water_charge": 800,
        "water_supply": True,
        "water_purifier": True,
        "fridge": True,
        "washing_machine": True,
        "CCTV": False,
        "guard": False,
        "medical": True,
        "fire_alarme": True,
        "cleaning": "No",
        "furnished": "FullyFurnished",
        "available_for": "Family",
        "available_from": "2021-05-30",
        "rent": 25000,
        "additional_charge": 0,
        "security_money": 50000,
        "one_time_charge": 0,
        "agreement_duration": 1,
        "owner_name": "Radhe",
        "owner_phone_no1": "6378384209",
        "owner_phone_no2": "",
        "posted_by": "Agent",
        "posted_on": "2021-05-31",
        "agent_name": "Pawan",
        "age_of_property": 2,
        "locality": "1.2km from Rose garden",
        "address": "Near Ooty botanical garden, Ooty",
        "city": "Ooty",
        "state": "Tamil Nadu",
        "pin": "643001",
        "user": 1
    },
    {
        "id": 2,
        "property_type": "Flat",
        "title": "2 BHK Apartment",
        "img1": "D:\RentAssure\RentAssure-Backend\media\\raw\\5.jpeg",
        "img2": "D:\RentAssure\RentAssure-Backend\media\\raw\\6.jpeg",
        "img3": "D:\RentAssure\RentAssure-Backend\media\\raw\\7.jpeg",
        "img4": "D:\RentAssure\RentAssure-Backend\media\\raw\\8.jpeg",
        "description": "Attractive and comfortable",
        "bhk": "2BHK",
        "bedroom": 2,
        "bathroom": 2,
        "balconies": 1,
        "Kitchen": 1,
        "area": 1500,
        "parking": False,
        "lift": False,
        "swimming_pool": False,
        "gym": False,
        "gas_pipeline": True,
        "electricity_charge": 1000,
        "electricity_supply": True,
        "Power_backup": False,
        "water_charge": 600,
        "water_supply": True,
        "water_purifier": True,
        "fridge": True,
        "washing_machine": False,
        "CCTV": False,
        "guard": False,
        "medical": True,
        "fire_alarme": True,
        "cleaning": "No",
        "furnished": "SemiFurnished",
        "available_for": "Any",
        "available_from": "2021-09-09",
        "rent": 15000,
        "additional_charge": 0,
        "security_money": 35000,
        "one_time_charge": 0,
        "agreement_duration": 2,
        "owner_name": "YC Builders",
        "owner_phone_no1": "6378384209",
        "owner_phone_no2": "",
        "posted_by": "Owner",
        "posted_on": "2021-05-31",
        "agent_name": None,
        "age_of_property": None,
        "locality": "Regional college",
        "address": "In front of Regional college",
        "city": "Ajmer",
        "state": "Rajasthan",
        "pin": "305004",
        "user": 1
    },
    {
        "id": 3,
        "property_type": "House",
        "title": "Sagar Villa",
        "img1": "D:\RentAssure\RentAssure-Backend\media\\raw\\9.jpeg",
        "img2": "D:\RentAssure\RentAssure-Backend\media\\raw\\10.jpeg",
        "img3": "D:\RentAssure\RentAssure-Backend\media\\raw\\11.jpeg",
        "img4": "D:\RentAssure\RentAssure-Backend\media\\raw\\12.jpeg",
        "description": "Its very big house with all facilities.",
        "bhk": "5+BHK",
        "bedroom": 6,
        "bathroom": 7,
        "balconies": 3,
        "Kitchen": 2,
        "area": 3200,
        "parking": True,
        "lift": False,
        "swimming_pool": True,
        "gym": True,
        "gas_pipeline": True,
        "electricity_charge": 4000,
        "electricity_supply": True,
        "Power_backup": False,
        "water_charge": 1000,
        "water_supply": True,
        "water_purifier": True,
        "fridge": True,
        "washing_machine": True,
        "CCTV": True,
        "guard": False,
        "medical": True,
        "fire_alarme": True,
        "cleaning": "No",
        "furnished": "FullyFurnished",
        "available_for": "Family",
        "available_from": "2021-07-17",
        "rent": 80000,
        "additional_charge": 0,
        "security_money": 100000,
        "one_time_charge": 0,
        "agreement_duration": 60,
        "owner_name": "Sagar  Jain",
        "owner_phone_no1": "6378384209",
        "owner_phone_no2": "",
        "posted_by": "Agent",
        "posted_on": "2021-05-31",
        "agent_name": "Pawan",
        "age_of_property": 24,
        "locality": "Located 1.3km from Calangute Beach",
        "address": "Nerul, Goa",
        "city": "Nerul",
        "state": "Goa",
        "pin": "403109",
        "user": 1
    },
    {
        "id": 4,
        "property_type": "Room",
        "title": "PG Morgan",
        "img1": "D:\RentAssure\RentAssure-Backend\media\\raw\\13.jpeg",
        "img2": "D:\RentAssure\RentAssure-Backend\media\\raw\\14.jpeg",
        "img3": "D:\RentAssure\RentAssure-Backend\media\\raw\\15.jpeg",
        "img4": "D:\RentAssure\RentAssure-Backend\media\\raw\\16.jpeg",
        "description": "Best room for anyone.",
        "bhk": "1RK/1BHK",
        "bedroom": 1,
        "bathroom": 1,
        "balconies": 1,
        "Kitchen": 0,
        "area": 1200,
        "parking": True,
        "lift": True,
        "swimming_pool": False,
        "gym": False,
        "gas_pipeline": False,
        "electricity_charge": 900,
        "electricity_supply": True,
        "Power_backup": False,
        "water_charge": 200,
        "water_supply": True,
        "water_purifier": True,
        "fridge": False,
        "washing_machine": False,
        "CCTV": True,
        "guard": False,
        "medical": True,
        "fire_alarme": False,
        "cleaning": "Daily",
        "furnished": "FullyFurnished",
        "available_for": "Any",
        "available_from": "2021-05-15",
        "rent": 9500,
        "additional_charge": 0,
        "security_money": 15000,
        "one_time_charge": 0,
        "agreement_duration": 2,
        "owner_name": "Dharmendra",
        "owner_phone_no1": "6378384209",
        "owner_phone_no2": "",
        "posted_by": "Owner",
        "posted_on": "2021-05-31",
        "agent_name": None,
        "age_of_property": None,
        "locality": "Vigyan Nagar",
        "address": "Vigyan Nagar, Vishal eye Hospital",
        "city": "Kota",
        "state": "Rajasthan",
        "pin": "324005",
        "user": 1
    },
    {
        "id": 5,
        "property_type": "Flat",
        "title": "Bhatia flats",
        "img1": "D:\RentAssure\RentAssure-Backend\media\\raw\\17.jpeg",
        "img2": "D:\RentAssure\RentAssure-Backend\media\\raw\\18.jpeg",
        "img3": "D:\RentAssure\RentAssure-Backend\media\\raw\\19.jpeg",
        "img4": "D:\RentAssure\RentAssure-Backend\media\\raw\\20.jpeg",
        "description": "Built in advanced Technology",
        "bhk": "2BHK",
        "bedroom": 2,
        "bathroom": 2,
        "balconies": 1,
        "Kitchen": 1,
        "area": 1600,
        "parking": True,
        "lift": True,
        "swimming_pool": False,
        "gym": False,
        "gas_pipeline": True,
        "electricity_charge": 1200,
        "electricity_supply": True,
        "Power_backup": False,
        "water_charge": 400,
        "water_supply": True,
        "water_purifier": True,
        "fridge": True,
        "washing_machine": True,
        "CCTV": False,
        "guard": False,
        "medical": True,
        "fire_alarme": True,
        "cleaning": "No",
        "furnished": "FullyFurnished",
        "available_for": "Any",
        "available_from": "2021-09-10",
        "rent": 19000,
        "additional_charge": 0,
        "security_money": 0,
        "one_time_charge": 0,
        "agreement_duration": 24,
        "owner_name": "Rajat Bhatia",
        "owner_phone_no1": "9664200250",
        "owner_phone_no2": "",
        "posted_by": "Agent",
        "posted_on": "2021-05-31",
        "agent_name": "Pawan",
        "age_of_property": 12,
        "locality": "Bennet University",
        "address": "In front of Bennet University",
        "city": "Greater Noida",
        "state": "Uttar Pradesh",
        "pin": "201310",
        "user": 1
    }
]


def add_data():
    print("add_data")
    try:
        print("try start")
        if len(DataModel.objects.all()):
            print("if")
            return 0

        for data in datas:
            DataModel.objects.create(
                property_type = data['property_type'],
                title = data['title'],
                img1 = data['img1'],
                img2 = data['img2'],
                img3 = data['img3'],
                img4 = data['img4'],
                description = data['description'],
                bhk = data['bhk'],
                bedroom = data['bedroom'],
                bathroom = data['bathroom'],
                balconies = data['balconies'],
                Kitchen = data['Kitchen'],
                area = data['area'],
                parking = data['parking'],
                lift = data['lift'],
                swimming_pool = data['swimming_pool'],
                gym = data['gym'],
                gas_pipeline = data['gas_pipeline'],
                electricity_charge = data['electricity_charge'],
                electricity_supply = data['electricity_supply'],
                Power_backup = data['Power_backup'],
                water_charge = data['water_charge'],
                water_supply = data['water_supply'],
                water_purifier = data['water_purifier'],
                fridge = data['fridge'],
                washing_machine = data['washing_machine'],
                CCTV = data['CCTV'],
                guard = data['guard'],
                medical = data['medical'],
                fire_alarme = data['fire_alarme'],
                cleaning  = data['cleaning'], 
                furnished = data['furnished'],
                available_for = data['available_for'],
                available_from = data['available_from'],
                rent = data['rent'],
                additional_charge = data['additional_charge'],
                security_money = data['security_money'],
                one_time_charge = data['one_time_charge'],
                agreement_duration = data['agreement_duration'],
                owner_name = data['owner_name'],
                owner_phone_no1 = data['owner_phone_no1'],
                owner_phone_no2 = data['owner_phone_no2'],
                posted_by = data['posted_by'],
                posted_on = data['posted_on'],
                agent_name = data['agent_name'],
                age_of_property = data['age_of_property'],
                locality = data['locality'],
                address = data['address'],
                city = data['city'],
                state = data['state'],
                pin = data['pin'],
                user_id  = data['user'], 
            )

        print("try end")
    except:
        print("except")
        pass
